name: CI
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11.5' # This will use the latest 1.x version, e.g., 1.10.x or 1.11.x
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # --- Add your HokseonRegistry ---
      - name: Add HokseonRegistry
        run: julia -e 'using Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/Louhokseson/HokseonRegistry.git"))'
        shell: bash

      # --- ADD THIS STEP: Add NQCRegistry because NQCModels (and thus NQCBase) needs it ---
      - name: Add NQCRegistry
        run: julia -e 'using Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/NQCD/NQCRegistry.git"))'
        shell: bash

      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        run: >
          julia --project=. --color=yes test/runtests.jl